### PR TITLE
 feat(XAI): Extending AUCMEDI XAI to cope with 3D data and batched inputs.

### PR DESCRIPTION
**Pull request by Deathlymad**

### CODE REVIEW

**Comment by Deathlymad** [comment]
- [ ] GradCAM
- [ ] GradCAM++
- [ ] Guided GradCAM
- [ ] Guided Backpropagation
- [ ] Integrated Gradients
- [ ] LIME
- [ ] Occlusion Sensitivity
- [ ] Saliency

**Comment by Deathlymad** [comment]
Guided GradCAM and the Decoder can probably be measurably accelerated by parallelizing the Resize operation or making it batch compatible.

**Comment by muellerdo** [comment]
Hey @Deathlymad,

please be aware that your git commits do not follow our git commit conventions.

Check out here:
https://frankkramer-lab.github.io/aucmedi/getstarted/contribution/#special-contribution-notes-for-aucmedi
and here:
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Deathlymad** [comment]
This was intended to update the commit messages. It appearsr that git misinterpreted the operation.

**Comment by Deathlymad** [comment]
Remaining Errors related to AutoML. Please advice on how to proceed.

**Comment by Deathlymad** [comment]
commited fix to this branch that should resolve issues related to pandas 2.0 update

**Comment by Deathlymad** [comment]
The coverage error is linked to a missing token

**Comment by muellerdo** [comment]
can you reset the last pandas commit for the evaluation on focusing on just the xai decoder? :)

avoiding large PRs changing various aspects and focusing on a one PR:one-issue-fix policy.

**Comment by Deathlymad** [comment]
@muellerdo reverted the pandas fix.
I believe that my edits are limited to the XAI files.

**Comment by muellerdo** [comment]
Stale, as batch-wise XAI decoder & methods revealed functionality issues.
Reopen if working solutions for these issues are found.

**Pull request closed without merging**
